### ISSUE TITLE
Format SSD

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-base#5]
Maybe move root partition over to SSD too? Decent looking instructions [here](https://www.tomshardware.com/news/boot-raspberry-pi-from-usb,39782.html).

**Comment by nathanielrindlaub** [comment]
Had permissions issues when mounted to media/, so maybe try mounting it within the animl user's directories? e.g. home/animl/data

**Comment by postfalk** [comment]
Yeah, don't mount to media. I think you have to do that as root. Not sure whether mounting to home folder is a good idea (since it is different for different  users). I would just make a directory /data in the root directory and mount it there. 

What file system are you using. I would suggest something generic like FAT32 in order to read the SSD drive on random USB ports of any operating system.

**Comment by postfalk** [comment]
FAT32 has a maximal file size of 4Gbyte. So exFat is better but has some issues (extra support settings on Linux). So exFAT would be great if we get it to work with Raspbian. See here https://pimylifeup.com/raspberry-pi-exfat/

On the other hand it might not that important for our experimenting but I also think it would be nice if people just could read the SSD on a PC in the field.

**Comment by nathanielrindlaub** [comment]
I had formatted to ext4 which seems to be the latest and greatest for Linux machines but yeah I don't think Mac or Windows can read it without additional software.

**Comment by postfalk** [comment]
Is the drive USB mounted in which case I would change it in the future. But for now that is ok.

**Comment by nathanielrindlaub** [comment]
I don't quite follow. The drive is currently fortmatted to ext4 and and mounted to /media/animl-drive, and I can add files to the mounted drive as my animl user, but the buckeye server software complains about permissions issues when I try to point it to use that drive to store the images. 

I can change any of that (reformat, mount it elsewhere, etc) if a different location makes more sense. I just chose /media because I read that's typically where you'd mount an external hardrive in a Linux system. But yeah still getting used to the user/groups/permissions stuff. Certainly a headache when you're not familiar with it.

**Comment by postfalk** [comment]
If you create the drive as you, the permissions on it will be just you. In order to make it reliable, you need to mount on startup as root and grant permission on the directory you mount to. Also the USB port where it is attached to might need to be hardwired to in the sense that its device address is actually stable. That is also something that might be to setup in the startup scripts. If you get stuck I might be able to dedicate some time to this.
